name: dscanner
version: 0.8.0
summary: Developer tool for analyzing D source code
description: |
  Provides many useful analytical tools for source code written in the
  D programming language, including statistics, style and syntax checks,
  definition searches, and generation of CTAGS and AST.
confinement: classic
grade: stable

apps:
  dscanner:
    command: bin/dscanner

parts:
  dscanner:
    source: https://github.com/dlang-community/D-Scanner.git
    source-tag: v0.8.0
    source-type: git
    plugin: make
    makefile: makefile
    make-parameters:
      - DMD=/snap/bin/dmd
    artifacts:
      - bin/dscanner
    build-snaps:
    - dmd
    build-packages:
    - build-essential
